package demo;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.util.Date;
import java.util.HashMap;

import java.io.IOException;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.io.LineNumberReader;
import java.nio.charset.StandardCharsets;

import wiki.TemplateParser;
import wiki.tools.WikiFormatter;
import wiki.tools.WikiPage;

/**
 * Swing application to show WikiParser capabilities
 * 
 * Compile: javac -encoding UTF-8 -cp .;lib\luaj-jse-3.0.2q.jar demo\WikiParserDemo.java
 * Run: java -cp .;lib\luaj-jse-3.0.2q.jar demo.WikiParserDemo
 *
 * This application requires files modules.dat and templates.dat generated by running WikiSplitter on https://dumps.wikimedia.org/simplewiktionary/latest/simplewiktionary-latest-pages-articles.xml.bz2
 * The Wikicode for the demo is taken from https://simple.wiktionary.org/wiki/time
 */
public class WikiParserDemo extends JFrame {

    private JTextArea inputArea;
    private JEditorPane displayArea;
    private Timer debounceTimer;
    private static final int UPDATE_DELAY_MS = 1000;

	final TemplateParser tp = new TemplateParser();
	final WikiPage wp;

	final static String linkBaseURL = "https://simple.wiktionary.org/wiki/";
	final static String initialDemoText = "== Noun ==\n{{noun}}\n# {{uncountable}} '''Time''' is what we [[measure]] with a [[clock]].\n#: ''\"What '''time''' do you finish work?\" \"At four [[o'clock]] (4:00).\"''\n#: ''I don't have '''time''' to talk to you right now. Can we do it later?''\n# {{countable}} If you do something one '''time''', you do it [[once]].\n== Verb ==\n{{verb|tim|e}}\n# {{transitive}} If you '''time''' something, you [[measure]] how long it takes in [[second]]s, [[minute]]s, [[hour]]s, etc.\n#: ''Take out your watch and '''time''' yourself during the test.''";
	final static String word = "time";

    public WikiParserDemo() {
		final HashMap<String, String> name2template = new HashMap<>();
		final HashMap<String, String> name2module = new HashMap<>();
		final HashMap<String, String> name2content = new HashMap<>();
		readfile(name2template, "demo/templates.dat", false);
		readfile(name2module, "demo/modules.dat", false);

		wp = new WikiPage(word,  new Date(),
			wiki.tools.Utilities.getLocale("en"), tp, name2template, name2module, false, name2content, true);

		setTitle("WikiParser demo");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout(10, 10));

		// Editable text field
        inputArea = new JTextArea(8, 80);
        inputArea.setLineWrap(true);
        inputArea.setWrapStyleWord(true);
		inputArea.setText(initialDemoText);
        JScrollPane inputScroll = new JScrollPane(inputArea);
        inputScroll.setBorder(BorderFactory.createTitledBorder("Input Text"));

        // Display area (read-only)
        displayArea = new JEditorPane();
        displayArea.setEditable(false);
        displayArea.setContentType("text/html");
        JScrollPane displayScroll = new JScrollPane(displayArea);
        displayScroll.setBorder(BorderFactory.createTitledBorder("Output"));
        displayScroll.setPreferredSize(new Dimension(400, 300));

        debounceTimer = new Timer(UPDATE_DELAY_MS, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateOutput();
            }
        });
        debounceTimer.setRepeats(false);

        inputArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { resetTimer(); }
            @Override
            public void removeUpdate(DocumentEvent e) { resetTimer(); }
            @Override
            public void changedUpdate(DocumentEvent e) { resetTimer(); }
        });

		add(inputScroll, BorderLayout.NORTH);
        add(displayScroll, BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);

		updateOutput();
    }

    private void resetTimer() {
        debounceTimer.restart();
    }

    private void updateOutput() {
        String input = inputArea.getText();
        if (input.isEmpty()) {
	        displayArea.setText("<html><body><i>Waiting for input...</i></body></html>");
        } else {
			try	{
				String formatted = WikiFormatter.formatWikiText(new StringBuilder(word), new StringBuilder(tp.parse(input, wp)), linkBaseURL, "en");
		        displayArea.setText(formatted);
				SwingUtilities.invokeLater(() -> {
					displayArea.setCaretPosition(0);
				});
			} catch (RuntimeException ex) {
					System.out.println("lemma:"+word);
					ex.printStackTrace();
			}
		}
    }

	public static String readfile(HashMap<String, String> name2page, String fn, boolean isWikiDat) {
		String firstline = null;
		try (LineNumberReader in = new LineNumberReader(new InputStreamReader(new FileInputStream(fn), StandardCharsets.UTF_8))) {
			StringBuilder definition = new StringBuilder();
			String st, identifier = "";
			String [] result;
			if (isWikiDat)
				firstline = in.readLine(); // read first line in wiki.dat
			int skiplines = 0;
			while((st = in.readLine()) != null) {
				if (skiplines > 0) {
					definition.append(st);
					skiplines--;
					if (skiplines == 0)	{
						assert !identifier.isEmpty();
						name2page.put(identifier, definition.toString());
						definition.setLength(0);
					} else definition.append("\n");
					continue;
				}
				if ((!st.contains("|"))) {
					System.out.println("Error1 Parsing in "+fn+": "+st);
					System.exit(1);
				}
				result = st.split("\\|");
				identifier =result[0].trim();
				try {
					skiplines = Integer.parseInt(result[1]);
				} catch (Exception ex) {
					System.out.println("Error2 Parsing in "+fn+": "+st);
					System.exit(1);
				}
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
		return firstline;//firstline is returned only in case of isWikiDat, otherwise null is returned
	}

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new WikiParserDemo().setVisible(true);
        });
    }
}